### ISSUE TITLE
Support groups of files inside segments

### ISSUE THREAD

**Issue by AngheloAlf** [decompals/slinky#34]
Instead of having this
```yaml
paths:
  base_path: build/us

segments:
- name: main_segment
  files:
  - { path: src/main_segment/replay.o }
  - { path: src/main_segment/066580.o }
  - { path: src/main_segment/066840.o }
  - { path: src/main_segment/unused/055C40.o }

  - { path: lib/libmus/src/player.o }
  - { path: lib/libmus/src/player_fx.o }
  - { path: lib/libmus/src/aud_dma.o }
  - { path: lib/libmus/src/aud_sched.o }
  - { path: lib/libmus/src/aud_thread.o }
  - { path: lib/libmus/src/lib_memory.o }
  - { path: lib/libmus/src/aud_samples.o }

  - { path: asm/rsp/rspboot.o }
  - { path: asm/rsp/aspMain.o }
  - { path: asm/rsp/f3dex2.o }
  - { path: asm/rsp/s2dex.o }
```

Allow to have this:
```yaml
paths:
  base_path: build/us

segments:
- name: main_segment
  files:
  # No group
  - { path: src/main_segment/replay.o }
  - { path: src/main_segment/066580.o }
  - { path: src/main_segment/066840.o }
  - { path: src/main_segment/unused/055C40.o }

  # One group
  - kind: group
    dir: lib/libmus/src/
    subfiles:
    - { path: player.o }
    - { path: player_fx.o }
    - { path: aud_dma.o }
    - { path: aud_sched.o }
    - { path: aud_thread.o }
    - { path: lib_memory.o }
    - { path: aud_samples.o }

  # Another group
  - kind: group
    dir: asm/rsp/
    subfiles:
    - { path: rspboot.o }
    - { path: aspMain.o }
    - { path: f3dex2.o }
    - { path: s2dex.o }
```

So the paths get appended, allowing to make the paths shorter. All those files would still be flattened when emitting the linker script
