### ISSUE TITLE
`dir` field for segments

### ISSUE THREAD

**Issue by AngheloAlf** [decompals/slinky#67]
Allow specifying a `dir` that would be prefixed to every file of the segment when emitting the linker script.

The following example should emit `build/src/battle/area/omo2_1/actor/shy_squad.o` as the file path.
```yaml
settings:
  base_path: build

segments:
  - name: omo2_1
    dir: src/battle/area/omo2_1
    files:
      - { path: actor/shy_squad.o }
```
