### ISSUE TITLE
Allow to only include or exclude specific sections from a file

### ISSUE THREAD

**Issue by AngheloAlf** [decompals/slinky#70]
This would allow finer control over the positioning of the sections of each file.

It should work without issues with section reordering ( decompals/slinky#44 ).

Compatibility with decompals/slinky#27 will be weird.

Syntax would look like something like this
```yaml

  - name: code
    files:
      - { path: src/code/main.o }
      - { path: src/code/z_message_PAL.o, only_sections: [.data], section_order: { .data: .rodata } }
      - { path: src/code/z_game_over.o, only_sections: [.data], section_order: { .data: .rodata } }
      - { path: src/code/z_message_PAL.o, exclude_sections: [.data] }
      - { path: src/code/z_game_over.o, exclude_sections: [.data] }
```

Combining `only_sections` and `exclude_sections` in the same entry should be illegal.
