### ISSUE TITLE
[Frug]: `section_order` does not work when used on files inside of `group`s

### ISSUE THREAD

**Issue by AngheloAlf** [decompals/slinky#71]
### Explain the problem.

Using `section_order: { .blah .urgh }` on a file entry that's inside a `group` kind doesn't override the global section order, instead it emits the entries in the original order.

### Reproducer

```yaml
segments:
  - name: example
    files:
      - { path: blehh.o }
      - kind: group
        files:
          - { path: src/rsp/rspboot.o }
          - { path: src/rsp/aspMain.o, section_order: { .data: .rodata } }
          - { path: src/rsp/f3dex2.o, section_order: { .data: .rodata } }
          - { path: src/rsp/s2dex.o, section_order: { .data: .rodata } }
```

### slinky flavour

cli built from source

### slinky version

0.1.0 commit 45b723b8242c74ae32516528e121585ec3580bde
